### ISSUE TITLE
I think there is bug - possibility of double loading

### ISSUE THREAD

**Issue by Perlover** [frandiox/vue-geo-suggest#3]
Hi,

I see the code:

https://github.com/frandiox/vue-geo-suggest/blob/479e0f8cde997767fa7558beee2fa9642211eea5/src/load-gmaps.js#L33

and

https://github.com/frandiox/vue-geo-suggest/blob/479e0f8cde997767fa7558beee2fa9642211eea5/src/load-gmaps.js#L39

I think the [`this` inside `function()`](https://github.com/frandiox/vue-geo-suggest/blob/479e0f8cde997767fa7558beee2fa9642211eea5/src/load-gmaps.js#L36) refers to `window` not to `window.initVGAMaps`

From [google docs](https://developers.google.com/maps/documentation/javascript/tutorial#Attributes):

> callback, where you specify the name of a global function to be called once the Maps JavaScript API loads completely

And from [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#Function_context) about `this` in fuctions:

> Inside a function, the value of this depends on how the function is called... this will default to the global object, which is window in a browser

So `window.initVGAMaps.loaded` will be always `undefined`

What do you think about this?

**Comment by frandiox** [comment]
@Perlover Thanks, I think you are right! I've checked the [reference code](https://github.com/xkjyeah/vue-google-maps/blob/master/src/manager.js) but it has already been updated a lot. Feel free to submit a PR, or other wise I'll fix it when I get some time.
